version: 2.1

jobs:
  build1:
    docker:
      - image: cimg/node:21.3.0
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: test-results

workflows:
  checkout_and_test:
    jobs:
      - build1:
          filters:
            branches:
              only:
                - main
